title: Eura Shin
logo: /assets/img/logo.jpg
email: eurashin [at] g [dot] harvard [dot] edu
show_downloads: false
show_links: true
google_analytics: G-C31QEPL8ER
google_scholar: https://scholar.google.com/citations?hl=en&user=S_eWDm0AAAAJ
linkedin: https://www.linkedin.com/in/eurashin/
github: https://github.com/eurashin
theme: jekyll-theme-minimal
